services:
  weather-dwh-postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
      - ./sql:/sql
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
